### ISSUE TITLE
Not able to read more than 9 tag values

### ISSUE THREAD

**Issue by uthaman** [marcopar/ethernetip4j#8]
Hi, when reading multiple tags using the example, it is not able to read more than 9 tags a time.

Below is the exception.

se.opendataexchange.ethernetip4j.exceptions.InvalidEncapsulationPackageException: Package can not be a valid Ethernet/IP Cip package.
    at se.opendataexchange.ethernetip4j.segments.CipPacketResponse.createPackage(CipPacketResponse.java:81)
    at se.opendataexchange.ethernetip4j.services.UnconnectedMessageManagerResponse.validate(UnconnectedMessageManagerResponse.java:50)
    at se.opendataexchange.ethernetip4j.clx.SimpleLogixCommunicator.read(SimpleLogixCommunicator.java:81)
    at se.opendataexchange.ethernetip4j.test.TestClass.main(TestClass.java:59)

**Comment by marcopar** [comment]
Sorry uthaman but i switched job and i don't work anymore with Allen Bradley plcs. Therefore i am unable to debug the case you mention.

Aniway I suggest to try to debug it by yourself and see if you can find the bug. Most of the time the errors I found in the past in the original library were due to wrong calculation of the packet length, wrong padding length and so on.

I will be happy to include the fix or add you in the project team if you wish.
The library has potential but it only lacks good developers
